### PR TITLE
Update and rename skr_no_diacritics.tsv to skr.tsv

### PR DESCRIPTION
**Pull request by mpQadir**
Corrected the entries of Saraiki language.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Thanks for the pull request, but why has one file been renamed and the other removed? We provide separate files with and without the pointing (diacritics); sometimes one wants diacritics or doesn't want diacritics. We do this for Hebrew too.

**Comment by mpQadir** [comment]
> Reference
In Saraiki there is no difference/ requirement for these two types. Both are same so one may be deleted please.

**Comment by mpQadir** [comment]
Reopen the pull request

**Comment by mpQadir** [comment]
It is requested that this be renamed and merged.

**Comment by kylebgorman** [comment]
As is our practice for languages written in (Perso-)Arabic script, we provide data with and without the tashkīl diacritics, in separate files. We do not intend to change this practice.

As you can see, in `skr_no_diacritics.tsv`, the number 21 is transcribed as اکی  and in `skr_with_diacritics.tsv` it is transcribed as اِکّی (note the kasrah and the ḍammah).

**Pull request closed without merging**
