### PR TITLE
Changed all misspellings and wrong numerals in Kashmiri (kas)

### PR DESCRIPTION
**Pull request by Rishabhbhat**
Nearly all spellings of the numbers were misspelt. Also changed the powers of 10 as the arab, kharab and lach were messed up; simply incorrect.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Thanks for your contribution; we'll take a look shortly. We can't integrate your PR unless you file the CLA (see bot post above) so please do that at your leisure.

**Comment by Rishabhbhat** [comment]
@kylebgorman is there any way to sign the CLA with a non-Google (specifically Yahoo!) email? The one associated with this account is on Yahoo!. Thanks.

**Comment by kylebgorman** [comment]
No idea, I just need one on file to review the PR.

**Comment by Rishabhbhat** [comment]
@kylebgorman I'm afraid I can't then. The CLA needs the Google account as well as the Github email to be the same. But they can't be. I'm really sorry, I didn't realise this when I created the pull request.

**Comment by kylebgorman** [comment]
Sorry to hear that and thanks for drawing our attention to it all the same.

**Comment by kylebgorman** [comment]
We resourced the numbers and have repaired them in 040408cae604c624af5c8b1ae25bf71ef25b7f55

**Pull request closed without merging**
